// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANLuxjbEFwPRUZvoc_4VPo0OBQCIYKUmc',
    appId: '1:589229581894:web:9c4a536056b16157a64c47',
    messagingSenderId: '589229581894',
    projectId: 'shop-78cad',
    authDomain: 'shop-78cad.firebaseapp.com',
    storageBucket: 'shop-78cad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALNjv_YdRWLhgvqLZibrcgY_o8oLQI45o',
    appId: '1:589229581894:android:64b384d3757c4917a64c47',
    messagingSenderId: '589229581894',
    projectId: 'shop-78cad',
    storageBucket: 'shop-78cad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdgOGaqmSRt1WfT0HFi_k_MeKxisx0Xvs',
    appId: '1:589229581894:ios:ec710dc87018982ba64c47',
    messagingSenderId: '589229581894',
    projectId: 'shop-78cad',
    storageBucket: 'shop-78cad.appspot.com',
    iosBundleId: 'com.example.shop',
  );
}
